message("*beep boop* loading libraries...")
suppressMessages(library(tidyverse))
suppressMessages(library(janitor))
suppressMessages(library(glue))
suppressMessages(library(ggtext))
suppressMessages(library(extrafont))
suppressMessages(library(here))
suppressMessages(library(httr))
message("*beep boop* libraries loaded!!")